import {
    Add20Filled,
    ArrowDown20Filled,
    ArrowMaximize20Filled,
    ArrowMinimize20Filled,
    Checkmark20Filled,
    ChevronRight20Filled,
    Circle20Regular,
    Dismiss20Filled,
    Home20Filled,
    Laptop20Filled,
    Navigation20Filled,
    Pause20Filled,
    Play20Filled,
    Settings20Filled,
    Subtract20Filled,
    WeatherMoon20Filled,
    WeatherSunny20Filled,
} from '@fluentui/react-icons';

export const Icons = {
    sun: WeatherSunny20Filled,
    moon: WeatherMoon20Filled,
    system: Laptop20Filled,
    right: ChevronRight20Filled,
    check: Checkmark20Filled,
    circle: Circle20Regular,
    home: Home20Filled,
    download: ArrowDown20Filled,
    settings: Settings20Filled,
    menu: Navigation20Filled,
    close: Dismiss20Filled,
    maximize: ArrowMaximize20Filled,
    restore: ArrowMinimize20Filled,
    minimize: Subtract20Filled,
    plus: Add20Filled,
    pause: Pause20Filled,
    play: Play20Filled,
};
